package app.zhijuan.core.model

enum class GenerationPhase {
    NORMALIZE_INPUT,
    BUILD_STORY_SEED,
    BUILD_BIBLE,
    BUILD_MASTER_OUTLINE,
    BUILD_ARC_PLAN,
    BUILD_CHAPTER_PLAN,
    ASSEMBLE_CONTEXT,
    DRAFT_CHAPTER,
    EXTRACT_MEMORY,
    CHECK_CONSISTENCY,
    REVISE_CHAPTER,
    COMMIT_CHAPTER,
    UPDATE_FUTURE_PLAN,
}

