package app.zhijuan.core.model

enum class RetryDisposition {
    WAIT_FOR_CONDITION,
    LIMITED_AUTOMATIC_RETRY,
    REPAIR_ONCE,
    CONTINUE_OUTPUT,
    USER_CONFIRMATION_REQUIRED,
    NEVER_AUTOMATICALLY,
}

enum class FailureRequestState {
    NOT_SENT,
    PROVIDER_REJECTED,
    RESPONSE_STARTED,
    RESULT_UNKNOWN,
}

enum class StandardErrorCode(
    val retryDisposition: RetryDisposition,
) {
    NETWORK_OFFLINE(RetryDisposition.WAIT_FOR_CONDITION),
    DNS_FAILED(RetryDisposition.LIMITED_AUTOMATIC_RETRY),
    TLS_FAILED(RetryDisposition.NEVER_AUTOMATICALLY),
    AUTH_FAILED(RetryDisposition.NEVER_AUTOMATICALLY),
    MODEL_NOT_FOUND(RetryDisposition.NEVER_AUTOMATICALLY),
    PROTOCOL_MISMATCH(RetryDisposition.NEVER_AUTOMATICALLY),
    RATE_LIMITED(RetryDisposition.LIMITED_AUTOMATIC_RETRY),
    QUOTA_EXHAUSTED(RetryDisposition.NEVER_AUTOMATICALLY),
    SERVER_OVERLOADED(RetryDisposition.LIMITED_AUTOMATIC_RETRY),
    POLICY_REFUSAL(RetryDisposition.NEVER_AUTOMATICALLY),
    CONTEXT_TOO_LARGE(RetryDisposition.REPAIR_ONCE),
    OUTPUT_TRUNCATED(RetryDisposition.CONTINUE_OUTPUT),
    FORMAT_INVALID(RetryDisposition.REPAIR_ONCE),
    STREAM_INTERRUPTED(RetryDisposition.USER_CONFIRMATION_REQUIRED),
    BUDGET_EXCEEDED(RetryDisposition.NEVER_AUTOMATICALLY),
    DAILY_BUDGET_PERIOD_EXPIRED_BEFORE_SEND(RetryDisposition.LIMITED_AUTOMATIC_RETRY),
    UNKNOWN_RESULT(RetryDisposition.USER_CONFIRMATION_REQUIRED),
    CREDENTIAL_UNAVAILABLE(RetryDisposition.NEVER_AUTOMATICALLY),
}
